# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow
name: Node.js and Solana CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: heyayushh/setup-anchor@v4.3
        with:
          # Install Solana CLI (beta, required to fix 'ahash' issue)
          node-version: "21.x"
          solana-cli-version: "1.18.22"
          anchor-version: "0.30.1"
          use-avm: "false"

      - name: Run Solana validator (and background it)
        run: solana-test-validator &

      - name: Install everything
        run: npm ci

      - name: Check Solana keygen is installed and Create a keypair
        run: |
          echo $PATH; which solana-keygen;
          solana config set --url localhost
          solana-keygen new --no-bip39-passphrase
          solana airdrop 3
        shell: bash

      - name: Run tests
        run: npm test
